# Generated by Django 2.1.5 on 2019-02-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_reg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reg',
            new_name='Registration',
        ),
    ]
