# Generated by Django 2.1.5 on 2019-02-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_reg', '0002_auto_20190203_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='first_name',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='second_name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
