# Generated by Django 2.1.5 on 2019-02-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_reg', '0003_auto_20190203_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='second_name',
            field=models.CharField(max_length=100),
        ),
    ]
