# Generated by Django 2.1.5 on 2019-02-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_reg', '0005_auto_20190203_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='second_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
