# Generated by Django 2.1.5 on 2019-02-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_reg', '0006_auto_20190203_1442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='User',
        ),
    ]
