# Generated by Django 2.1.5 on 2019-02-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_reg', '0008_auto_20190205_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.EmailField(max_length=254),
        ),
    ]
