# Generated by Django 2.1.5 on 2019-02-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_reg', '0009_auto_20190205_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
