# Generated by Django 2.1.5 on 2019-02-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_reg', '0012_auto_20190207_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
