# Generated by Django 2.1.5 on 2019-03-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190312_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='asdf_asdf', max_length=40, null=True),
        ),
    ]
