# Generated by Django 2.1.5 on 2019-02-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='nmb',
            new_name='amount',
        ),
    ]
