# Generated by Django 2.1.5 on 2019-03-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190305_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('o', 'Old')], default='n', max_length=50),
        ),
    ]
